### ISSUE TITLE
No way to distinguish between file and directory in ignore callback

### ISSUE THREAD

**Issue by MikeJerred** [fabiospampinato/watcher#11]
The ignore callback just gets a path, but it can be helpful for ignore rules to know if that path is for a directory or a file. Of course, you could do a file stat to find out, but that would presumably be very inefficient. If this information is already available to Watcher it would be good to pass it in the ignore function handler.

**Comment by fabiospampinato** [comment]
It would be good, but the library only prods the filesystem for stats objects after asking you if the path should be ignored or not. Supporting both use cases is a bit out of scope, and between the two I prefer the current one as it can be more efficient.

**Comment by fabiospampinato** [comment]
In general failing to ignore some files doesn't matter much, you can always ignore events for them at the app level later on. Ignoring folders is more important as they can contain arbitrarily many files, if `/foo` is a big folder you'll be asked if you want to ignore `/foo/a`, `/foo/b` etc. in which case the path tells you that `/foo` was in fact a folder, all without prodding the filesystem unnecessarily.
