### ISSUE TITLE
Seeking advice regarding integrating file watcher into an asynchronous-based application.

### ISSUE THREAD

**Issue by jeffschwartz** [fabiospampinato/watcher#15]
As the title says, I am developing a non web Node app and like most modern apps it is very asynchronous and uses async and await as well as promises. The issue I am having is how I can  expose my apps' async methods to be called by some file event triggered by the file watcher which doesn't support asynchronous event handlers. I'm hoping that someone can provide some insights into finding a solution.

**Comment by fabiospampinato** [comment]
Watcher only cares that you give it a function as an event handler I think, if it's synchronous or asynchronous it doesn't matter, it just calls it. So potentially you could do like:

```ts
watcher.on ( event, async () => {
 // Do something
});
```
