### ISSUE TITLE
Reading a file will trigger a change event

### ISSUE THREAD

**Issue by Dr-Harris** [fabiospampinato/watcher#19]
#### Step 1：watch a folder  (index.js)
``` js
import Watcher from "watcher";
const watcher = new Watcher("D:/code", {
  ignoreInitial: true,
  recursive: true,
});
watcher.on("all", (event, targetPath) => {
  console.log(event, targetPath);
});
watcher.on("ready", () => {
  console.log("watcher is ready");
});
```
run `node index.js`
#### Step 2：read any file in this folder(readfile.js)
``` js
import fs from "fs";
let content = fs.readFileSync("D:/code/a/b/c.js", "utf-8");
console.log(content);
```
run `node readfile.js`
#### Step 3：index.js 's output is:
```
watcher is ready
change D:/code/a/b/c.js
```

environment：win11 x64、node v16.20

**Comment by fabiospampinato** [comment]
If you see a change event the watcher probably received one, I guess `fs.readFileSync` is updating metadata on the file or something.
