### ISSUE TITLE
TypeScript type errors on import

### ISSUE THREAD

**Issue by itaylor** [fabiospampinato/watcher#2]
When I use this library I get the following when running `tsc` (using version 4.1.3):
```
node_modules/watcher/dist/watcher_handler.d.ts:7:14 - error TS2709: Cannot use namespace 'Watcher' as a type.

7     watcher: Watcher;
               ~~~~~~~

node_modules/watcher/dist/watcher_handler.d.ts:13:26 - error TS2709: Cannot use namespace 'Watcher' as a type.

13     constructor(watcher: Watcher, config: WatcherConfig, base?: WatcherHandler);
                            ~~~~~~~
```

I can work around this by adding `skipLibCheck: true` to my `tsconfig.json`, it really shouldn't be necessary.

I think the issue is caused by the use of:
```
import Watcher from './watcher';
```
Watcher is both the default export and the namespace.

Changing `watcher_handler.d.ts` so that it imports the type not the default export:
```
import { type as Watcher } from './watcher';
```
Fixes it.

**Comment by fabiospampinato** [comment]
I can't quite reproduce the issue:

<img width="346" alt="Screen Shot 2021-04-01 at 22 14 06" src="https://user-images.githubusercontent.com/1812093/113354793-9a87af80-9337-11eb-8037-825cc620afbf.png">

I just see no errors and I don't have skipLibCheck enabled.

If you can make a repro I'll take a second look at this, but "skipLibCheck" is kind of a must anyway.

**Comment by daniel-brenot** [comment]
> 

Skiplibcheck should not be a "must". I'm encountering the same issue here. The 'on' method doesn't even show up for me.

**Comment by fabiospampinato** [comment]
I think this should be fixed.
