### ISSUE TITLE
filter metadata change

### ISSUE THREAD

**Issue by yyy19961027** [fabiospampinato/watcher#21]
How to filter changes to metadata

![微信图片_20230605114519](https://github.com/fabiospampinato/watcher/assets/66300848/84f2a47b-d271-4697-9845-5e850d8c08f1)

**Comment by fabiospampinato** [comment]
That's not supported, because it would require checking if the actual content of the file changed or not, which is too expensive for the library to do. If you need that you can implement that in your app.
