### ISSUE TITLE
Watch network shares

### ISSUE THREAD

**Issue by mheberlein** [fabiospampinato/watcher#24]
Will this watcher work on network shares, soo?

I'm looking for a solution that will watch local folders as well as SMB shares recursively.

I should be possible via e.g. `smbclient notify`:

https://www.samba.org/samba/docs/current/man-html/smbclient.1.html

https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-fasod/271a36e8-c94b-4527-8735-e884f5504cd9

**Comment by fabiospampinato** [comment]
I don't think it would. I'd use [pollex](https://github.com/fabiospampinato/pollex) for that and other niche use cases.
