### ISSUE TITLE
How to make this package work in electron main processes? Enable the CommonJs Require

### ISSUE THREAD

**Issue by Muhammad-Taif-Khan** [fabiospampinato/watcher#25]
I used to use the **@1.2.0v** of this package with require() syntax in **electronjs main process**. But now the package has transformed to use esm. Which I could not make to work.

**Enable the CommonJs require too🙏**

- OS: Windows 11
- Electron: 22.0.0

**Comment by fabiospampinato** [comment]
I don't publish CommonJS modules anymore, and v1 of this module is no longer supported. You should bundle your main process code to CommonJS with something like esbuild.
