### ISSUE TITLE
TypeError: Watcher is not a constructor

### ISSUE THREAD

**Issue by kodelio** [fabiospampinato/watcher#26]
Hello,

I'm trying to use the package with Electron, I'm getting this error : 
`TypeError: Watcher is not a constructor`

Here's how I'm importing the package (because require isn't working) : 
`const Watcher = await import("watcher");`

Any idea or solution to solve this ? Thanks

**Comment by fabiospampinato** [comment]
it should be `(await import('watcher')).default` I guess. But really worth just switching to ESM, then you can just do `import Watcher from "watcher"`
