### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by cuginoAle** [fabiospampinato/watcher#30]
Hi,
thanks for this great tool!
I was successfully using it on a Node Js project and it was working smoothly.
I am now converting that project to use TS  but now I get this error at build time:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_ts/node_modules/watcher/dist/watcher.js
from .../dist/data.js not supported.
Instead change the require of watcher.js in .../dist/data.js to a dynamic import() which is available in all CommonJS modules.
```

Is this a known issue or am I doing something wrong?

best!

**Comment by fabiospampinato** [comment]
Basically this is an ESM-only package, so it can't be "require()"d.

I've switched fully to ESM, so I don't really care about CJS anymore. I guess you'd need some bundling step, or to switch to ESM yourself, to use `watcher`. Not an ideal situation, but I've switched to ESM myself precisely to avoid all these issues.
