### ISSUE TITLE
Question: run once and stop watching?

### ISSUE THREAD

**Issue by pdaoust** [fabiospampinato/watcher#36]
I'd love to use this in my build script that has a `--watch` option, and it works great with that, but I'd also love to not have to write a separate code path to traverse the directory tree for non-watching mode. Is it possible to tell watcher to run once on all existing files, then exit?

**Comment by fabiospampinato** [comment]
That's not possible today, #10 would need to be fixed to be able to implement that. I guess you can track that issue for this, but I wouldn't recommend using `watcher` just for discovering files, as it would create a bunch of unnecessary filesystem watchers that you don't really want to pay for if you just want to discover files.
