### ISSUE TITLE
Update versions of Node tested on CI

### ISSUE THREAD

**Issue by benmccann** [fabiospampinato/watcher#41]
Node 20 and 22 are out and should be added to the CI

@fabiospampinato do you want to keep Node 16 on the CI, which is now EOL?

Also, I saw that Node 20 added native recursive watching support on Linux, so if you're open to dropping versions before Node 20.12 ([where Linux watching was fixed to actually work](https://nodejs.org/en/blog/release/v20.12.0)) we could potentially delete some code. Or would you prefer the watcher to check which version of Node is being run instead?

**Comment by benmccann** [comment]
Although having more versions is helpful at the moment due to test flakiness. I added Node 20 and 22 in https://github.com/fabiospampinato/watcher/pull/40 and left 16 and 18. Currently 1/4 versions are passing on Linux. Having four versions help us see that at least one is working. Perhaps we should address the flakiness before removing older versions

**Comment by fabiospampinato** [comment]
Let's just switch to v20 as the minimum version, which adds support for native watching for linux. https://github.com/fabiospampinato/watcher/commit/9e27139a5b83e5378f9f0ab98094e9e84790a805

**Comment by fabiospampinato** [comment]
Actually what you are doing in #42 seems better, no need to drop support for v18.
