### ISSUE TITLE
rename detection without timeout

### ISSUE THREAD

**Issue by benmccann** [fabiospampinato/watcher#43]
It seems the current implementation depends on a timeout. Is it possible to avoid this at least in some cases such as when the native watcher is used?

- inotify has `IN_MOVED_FROM` and `IN_MOVED_TO`
- Node's native `fs.watch` has an `eventType` which is either `'change'` or `'rename'`. [It fires for both the old location and new location](https://stackoverflow.com/questions/55296834/how-to-use-nodejs-to-find-out-file-rename-event). Though it seems [this is how the underlying inotify API works](https://stackoverflow.com/questions/5000880/can-inotify-tell-me-where-a-monitored-file-is-moved)
- Perhaps using `inode` number together with `birthtime`? (https://github.com/paulmillr/chokidar/issues/303#issuecomment-290450388)

**Comment by benmccann** [comment]
Turns out that `'rename'` fires twice. Once for the old location and once for the new location: https://stackoverflow.com/questions/55296834/how-to-use-nodejs-to-find-out-file-rename-event

**Comment by benmccann** [comment]
I think it's basically impossible. `inotify` just doesn't support it

- https://stackoverflow.com/questions/16204646/does-inotify-group-in-moved-from-and-in-moved-to
- https://stackoverflow.com/questions/20300955/detecting-foreign-in-moved-from-renames-with-inotify

I'm less clear on whether `fanotify` might support it, but the `fanotify` API looks quite similar to the `inotify` API, so I don't necessarily expect a different result there

**Comment by benmccann** [comment]
Actually, I think you can do this using `fanotify`:

>The event FAN_RENAME may contain two information records. One of type FAN_EVENT_INFO_TYPE_OLD_DFID_NAME identifying the old directory entry, and another of type FAN_EVENT_INFO_TYPE_NEW_DFID_NAME identifying the new directory entry.

**Comment by benmccann** [comment]
A couple issues with `fanotify`:
- you'd need a native implementation to use it unless Node.js implements support for it
- it can be tricky to use together with docker (https://github.com/parcel-bundler/watcher/issues/87#issuecomment-2127665211)

**Comment by fabiospampinato** [comment]
Yeah I think this is impossible right now given that a goal of the project is to have zero native dependencies like that (unlike stuff like chokidar).

It would be ideal though, happy to reopen if it ever becomes possible.
