### ISSUE TITLE
Cannot use with Electron anymore

### ISSUE THREAD

**Issue by phlegmaticprogrammer** [fabiospampinato/watcher#44]
I was using watcher happily with Electron until a few months ago. Then an update of electron-forge came, stuff broke, and I stopped development of the app. Now I am back, but somehow only commonjs packages seem to work now. My own packages work with both commonjs and ESM, but watcher doesn't, and has all of these little dependencies that make it a pain to convert (what is "tsex"??). 

It is the only external dependency in my project, but I think I will have to remove it now and write a watcher myself instead.

**Comment by phlegmaticprogrammer** [comment]
I've forked everything, and removed tsex and replaced it with ESNext/commonjs config.

**Comment by fabiospampinato** [comment]
I'd recommend just bundling your main process code to CJS.
