### ISSUE TITLE
CommonJS

### ISSUE THREAD

**Issue by zyang19** [fabiospampinato/watcher#45]
I want to request a feature that would allow the library to work using `require`

**Comment by fabiospampinato** [comment]
Sorry I moved on from CommonJS, I don't plan on supporting it anymore in the future. A future version of Node will include the ability to require non-top-level-await ESM packages though, so this should probably fix itself I guess.

**Comment by emcodem** [comment]
@fabiospampinato I would like to second this, i am sure lots of huge existing projects would don't plan to change to ejs modules or update node very soon

**Comment by fabiospampinato** [comment]
Sorry I decided to 100% move on from CJS, I have no intention of supporting that from any on my packages anymore.
