### ISSUE TITLE
Feature: Add usePolling option  

### ISSUE THREAD

**Issue by m0nzderr** [fabiospampinato/watcher#46]
Sometimes there are use cases when we have to watch files on filesystems like NFS, which do not support cross-network events. It would be very handy to have an option, similar to the chokidars' usePolling flag to forcedly switch to polling in such scenarios.

**Comment by fabiospampinato** [comment]
I consider this a bit out of scope because watching recursively via polling is kind of a different kind of watching, I have a different module for that that embraces that: https://github.com/fabiospampinato/pollex
