### ISSUE TITLE
Can't Seem to use "on" events

### ISSUE THREAD

**Issue by thecrazytech1** [fabiospampinato/watcher#47]
I get `Property 'on' does not exist on type 'Watcher'. Did you mean to access the static member 'Watcher.on' instead?` and I am using typescript and the examples on the README (like below)
```ts
watcher.on("ready", () => {
   console.log("Watcher Started!")
});
```

lemme know what else you may need

**Comment by emcodem** [comment]
are you sure you are using the class "instance" instead of e.g. the class itself?
```
const watcher = new Watcherinstance ( ['/foo/bar', '/baz/qux'] );
Watcherinstance.on(........)
```

**Comment by fabiospampinato** [comment]
Most probably user error, but happy to reopen if a repro is provided.
