### ISSUE TITLE
Renaming not triggering proper events with different character cases

### ISSUE THREAD

**Issue by silverkorn** [fabiospampinato/watcher#5]
Hi,

When I rename a file with the same name but with different cases, such as `test.txt` -> `Test.txt`, unlike other renaming behaviors, such as `test.txt` -> `test2.txt`, the events triggered are "`change` + `add`" instead of an "`unlink` + `add`".

Occurred with:
- Windows 10 Professional (20H2)
- Node v12.22.1 & v14.17.2
- Watcher v1.2.0
- `renameDetection` is and must be disabled in my case but using it doesn't work either and also returns a "`change` + `add`"

Thanks!

**Comment by fabiospampinato** [comment]
That sure sounds like a bug, I'll look into that, thanks for reporting the issue!

> renameDetection is and must be disabled in my case

Can you expand a little bit more on that? In particular has that to do with Watcher not being good enough for your use case?

**Comment by silverkorn** [comment]
Oh, don't worry about this! 
The "must" is just that I've programmed it in a way that it's less redundant using only `add` and `unlink` rather than implementing additional events when those two already does the job properly together in this case. (It's a synchronization application)

Thanks again!

Edit: After thoughts, it's be better to implement it to avoid useless transfers, thanks for letting me question myself about it! 😁

**Comment by fabiospampinato** [comment]
Implemented in v2.1.0. It was a bit tricky to implement, but pretty cool that it's detectable too.
