### ISSUE TITLE
Watcher hung on initializing windows 10

### ISSUE THREAD

**Issue by advplyr** [fabiospampinato/watcher#8]
I have been using Watcher for a while without issue.

I'm initializing a watcher with 1 folder that contains 2000 folders, each with 1 sub folder that has a few files.

I put a few console logs in and saw the watcher is getting hung in tiny-readdir here: https://github.com/fabiospampinato/tiny-readdir/blob/master/src/index.ts#L35

In testing I increased the concurrency limit over 2k and it finished initialization.

No symlinks and the config is
```js
{
  ignored: /(^|[\/\\])\../, // ignore dotfiles
  renameDetection: true,
  renameTimeout: 2000,
  recursive: true,
  ignoreInitial: true,
  persistent: true
}
```

**Comment by fabiospampinato** [comment]
- How long does it take without raising the concurrency limit?
- And how long with the limit raised to 2000?
- Could you share a performance profile of this? You can get one by `node --inspect-brk`-ing your script, opening the devtools via the link from `chrome://inspect`, and recording one from there.

**Comment by advplyr** [comment]
It is very fast when there is no concurrency limit or the concurrency limit is greater than the number of directories.

I did a bit more digging and I see what is happening.

In the promise-concurrency-limiter the promise never finishes because the nested directory gets queued.

i.e.
```
/dirA/subdir/...
/dirB/subdir/...
/dirC/subdir/...
```
Suppose the concurrency limit is 1.
`/dirA` runs, `/dirB` gets queued, `/dirC` gets queued, `/dirA/subdir` gets queued. Since the subdir just got queued the promise from `/dirA` never returns.


One possible solution in tiny-readdir could be
```js
  const handleDirectory = ( dirmap: ResultDirectory, subPath: string, depth: number ): Promisable<void> => {

    dirmap.directories.push ( subPath );
    directories.push ( subPath );

    if ( depth >= maxDepth ) return;
   
    // if depth > 1 and the limiter is full, then we cannot queue this function or the current promise will never return
    if ( depth > 1 && limiter.count >= limiter.concurrency) return populateResultFromPath ( subPath, depth + 1 )

    return limiter.add ( () => populateResultFromPath ( subPath, depth + 1 ) );

  };
```
https://github.com/fabiospampinato/tiny-readdir/blob/master/src/index.ts#L28

**Comment by beorn** [comment]
Any update on this?

**Comment by fabiospampinato** [comment]
I've removed the concurrency limiter, which slowed things down and caused deadlocks potentially.

It seems that `tiny-readdir` naturally yields to the event loop due to internal async/awaits, so the limiter is not really needed for that. For edge cases where the user is asking to watch `/` or something, where `tiny-readdir` could almost freeze the process, I've added a `limit` option, both to that and to watcher, there's basically no limit by default, but depending on your use case you may decide to set one yourself as a stop gap measure in edge cases.

Thanks for reporting the issue 👍
